#!/bin/sh
nohup rabbitmq-server -detached


export ROBOTREVIEWER_GROBID_PATH="/var/lib/deploy/grobid-0.5.1"
export ROBOTREVIEWER_GROBID_HOST="http://0.0.0.0:8070"
export DEV false
export DEBUG false
export KERAS_BACKEND=tensorflow
cd /var/lib/deploy/ && nohup bert-serving-start -model_dir /var/lib/deploy/robotreviewer/data/scibert_scivocab_uncased -num_worker=1 &
sleep 2
cd /var/lib/deploy/ && nohup celery -A robotreviewer.ml_worker worker --loglevel=info --concurrency=1 --pool=solo &
cd /var/lib/deploy/ && nohup python /var/lib/deploy/server.py &
sleep infinity 
