#!/bin/sh
rabbitmq-server --detatched

export ROBOTREVIEWER_GROBID_PATH="/var/lib/deploy/grobid-grobid-parent-0.4.1"
export ROBOTREVIEWER_GROBID_HOST="http://0.0.0.0:8080"
export DEV false
export DEBUG false
export KERAS_BACKEND=theano

su deploy -c 'cd /var/lib/deploy/ && nohup celery -A robotreviewer.ml_worker worker --loglevel=info &'
su deploy -c 'cd /var/lib/deploy/ && nohup python /var/lib/deploy/server.py &'
sleep infinity
